In [4]:
import numpy as np

***Partial Cleaning While Importing - Exercise #1***
Using the arguments of the np.genfromtxt() function, perform the following data cleaning steps:
1. Set the data type to string.
2. Skip the first row of the dataset.
3. Skip the last 15 rows of the dataset.
4. Load only the 2nd, 3rd, and 5th columns.

In [5]:
lending_co_TP = np.genfromtxt("Lending-Company-Total-Price-100.csv", 
                              delimiter = ',', 
                              dtype = str,
                              skip_header= 1,
                              skip_footer=15,
                              usecols=(1,3,4))

print(lending_co_TP)

[['id_1' 'Male' 'Location 2']
 ['id_2' 'Male' 'Location 3']
 ['id_3' 'Female' 'Location 5']
 ['id_4' 'Male' 'Location 6']
 ['id_5' 'Female' 'Location 7']
 ['id_6' 'Female' 'Location 10']
 ['id_7' 'Male' 'Location 11']
 ['id_8' 'Male' 'Location 12']
 ['id_9' 'Female' 'Location 3']
 ['id_10' 'Female' 'Location 13']
 ['id_11' 'Female' 'Location 15']
 ['id_12' 'Female' 'Location 16']
 ['id_13' 'Male' 'Location 17']
 ['id_14' 'Male' 'Location 19']
 ['id_15' 'Female' 'Location 23']
 ['id_16' 'Male' 'Location 27']
 ['id_17' 'Male' 'Location 25']
 ['id_18' 'Female' 'Location 26']
 ['id_19' 'Male' 'Location 29']
 ['id_20' 'Male' 'Location 30']
 ['id_21' 'Male' 'Location 31']
 ['id_22' 'Male' 'Location 17']
 ['id_23' 'Male' 'Location 33']
 ['id_24' 'NotSpecified' 'Location 34']
 ['id_25' 'Female' 'Location 35']
 ['id_26' 'Male' 'Location 37']
 ['id_27' 'Female' 'Location 38']
 ['id_28' 'Female' 'Location 39']
 ['id_29' 'Female' 'Location 40']
 ['id_30' 'Male' 'Location 30']
 ['id_31' 'Male' 'Location 41']
 ['id_32' 'Male' 'Location 42']
 ['id_33' 'Female' 'Location 22']
 ['id_34' 'Male' 'Location 43']
 ['id_35' 'Female' 'Location 46']
 ['id_36' 'Female' 'Location 47']
 ['id_37' 'Male' 'Location 50']
 ['id_38' 'Male' 'Location 26']
 ['id_39' 'NotSpecified' 'Location 52']
 ['id_40' 'Female' 'Location 25']
 ['id_41' 'Male' 'Location 17']
 ['id_42' 'Female' 'Location 19']
 ['id_43' 'Male' 'Location 53']
 ['id_44' 'NotSpecified' 'Location 54']
 ['id_45' 'Male' 'Location 46']
 ['id_46' 'Male' 'Location 44']
 ['id_47' 'Male' 'Location 39']
 ['id_48' 'Male' 'Location 30']
 ['id_49' 'Male' 'Location 56']
 ['id_50' 'Female' 'Location 44']
 ['id_51' 'Male' 'Location 57']
 ['id_52' 'Female' 'Location 39']
 ['id_53' 'Male' 'Location 59']
 ['id_54' 'Male' 'Location 44']
 ['id_55' 'Male' 'Location 60']
 ['id_56' 'Male' 'Location 29']
 ['id_57' 'Female' 'Location 44']
 ['id_58' 'Male' 'Location 61']
 ['id_59' 'Male' 'Location 62']
 ['id_60' 'Female' 'Location 6']
 ['id_61' 'Male' 'Location 23']
 ['id_62' 'NotSpecified' 'Location 64']
 ['id_63' 'Female' 'Location 65']
 ['id_64' 'Male' 'Location 66']
 ['id_65' 'Male' 'Location 23']
 ['id_66' 'Male' 'Location 19']
 ['id_67' 'Male' 'Location 50']
 ['id_68' 'Male' 'Location 68']
 ['id_69' 'Female' 'Location 61']
 ['id_70' 'Female' 'Location 10']
 ['id_71' 'Female' 'Location 64']
 ['id_72' 'Male' 'Location 70']
 ['id_73' 'Male' 'Location 72']
 ['id_74' 'Male' 'Location 40']
 ['id_75' 'Male' 'Location 20']
 ['id_76' 'Male' 'Location 73']
 ['id_77' 'Female' 'Location 20']
 ['id_78' 'Male' 'Location 75']
 ['id_79' 'Male' 'Location 76']
 ['id_80' 'Female' 'Location 77']
 ['id_81' 'Male' 'Location 2']
 ['id_82' 'Male' 'Location 4']
 ['id_83' 'Female' 'Location 78']
 ['id_84' 'Male' 'Location 79']
 ['id_85' 'Female' 'Location 80']]

*** Partial Cleaning While Importing - Exercise #2 ***
Now that you understand how the np.genfromtext() function works, set its parameters with the following arguments in the given code (lines 4 to 15 inclusive):
1. Use a comma as the delimiter for the dataset.
2. Set the data type of the values to string.
3. Skip the first row of the dataset.
4. Skip the last fifteen rows of the dataset.
5. Load only the second, third, and fifth columns from "Lending-Company-Total-Price-100.csv".
6. Use # to indicate the start of a comment.
7. Indicate that no data conversions are required (i.e., leave converters=None).
8. Ensure that only empty fields are treated as missing data.
9. Ensure that no field names are excluded from the retrieved dataset.
10. Remove the following characters from field names: ()*+,-./:;<=>?@[\\]^{|}~
11. Replace whitespaces in field names with underscores.
12. Automatically strip leading and trailing whitespaces from field names.

In [6]:
lending_co_TP = np.genfromtxt("Lending-Company-Total-Price-100.csv",
                              delimiter= ',', 
                              dtype=str,
                              skip_header=1,
                              skip_footer=15,
                              usecols=(1,2,4),
                              comments="#",
                              converters=None,
                              missing_values=None,
                              filling_values="0",
                              excludelist=None,
                              deletechars="()*+,-./:;<=>?@[\\]^{|}~",
                              replace_space="_",
                              autostrip=True)
                         
print(lending_co_TP)

[['id_1' 'Product B' 'Location 2']
 ['id_2' 'Product B' 'Location 3']
 ['id_3' 'Product C' 'Location 5']
 ['id_4' 'Product B' 'Location 6']
 ['id_5' 'Product D' 'Location 7']
 ['id_6' 'Product B' 'Location 10']
 ['id_7' 'Product A' 'Location 11']
 ['id_8' 'Product B' 'Location 12']
 ['id_9' 'Product A' 'Location 3']
 ['id_10' 'Product A' 'Location 13']
 ['id_11' 'Product B' 'Location 15']
 ['id_12' 'Product D' 'Location 16']
 ['id_13' 'Product B' 'Location 17']
 ['id_14' 'Product A' 'Location 19']
 ['id_15' 'Product A' 'Location 23']
 ['id_16' 'Product B' 'Location 27']
 ['id_17' 'Product A' 'Location 25']
 ['id_18' 'Product B' 'Location 26']
 ['id_19' 'Product B' 'Location 29']
 ['id_20' 'Product E' 'Location 30']
 ['id_21' 'Product B' 'Location 31']
 ['id_22' 'Product A' 'Location 17']
 ['id_23' 'Product A' 'Location 33']
 ['id_24' 'Product C' 'Location 34']
 ['id_25' 'Product D' 'Location 35']
 ['id_26' 'Product A' 'Location 37']
 ['id_27' 'Product A' 'Location 38']
 ['id_28' 'Product F' 'Location 39']
 ['id_29' 'Product D' 'Location 40']
 ['id_30' 'Product B' 'Location 30']
 ['id_31' 'Product B' 'Location 41']
 ['id_32' 'Product B' 'Location 42']
 ['id_33' 'Product A' 'Location 22']
 ['id_34' 'Product B' 'Location 43']
 ['id_35' 'Product A' 'Location 46']
 ['id_36' 'Product B' 'Location 47']
 ['id_37' 'Product B' 'Location 50']
 ['id_38' 'Product B' 'Location 26']
 ['id_39' 'Product C' 'Location 52']
 ['id_40' 'Product B' 'Location 25']
 ['id_41' 'Product B' 'Location 17']
 ['id_42' 'Product B' 'Location 19']
 ['id_43' 'Product A' 'Location 53']
 ['id_44' 'Product C' 'Location 54']
 ['id_45' 'Product A' 'Location 46']
 ['id_46' 'Product B' 'Location 44']
 ['id_47' 'Product B' 'Location 39']
 ['id_48' 'Product B' 'Location 30']
 ['id_49' 'Product D' 'Location 56']
 ['id_50' 'Product A' 'Location 44']
 ['id_51' 'Product B' 'Location 57']
 ['id_52' 'Product A' 'Location 39']
 ['id_53' 'Product D' 'Location 59']
 ['id_54' 'Product B' 'Location 44']
 ['id_55' 'Product B' 'Location 60']
 ['id_56' 'Product B' 'Location 29']
 ['id_57' 'Product B' 'Location 44']
 ['id_58' 'Product B' 'Location 61']
 ['id_59' 'Product B' 'Location 62']
 ['id_60' 'Product B' 'Location 6']
 ['id_61' 'Product A' 'Location 23']
 ['id_62' 'Product C' 'Location 64']
 ['id_63' 'Product C' 'Location 65']
 ['id_64' 'Product D' 'Location 66']
 ['id_65' 'Product B' 'Location 23']
 ['id_66' 'Product A' 'Location 19']
 ['id_67' 'Product A' 'Location 50']
 ['id_68' 'Product D' 'Location 68']
 ['id_69' 'Product A' 'Location 61']
 ['id_70' 'Product B' 'Location 10']
 ['id_71' 'Product C' 'Location 64']
 ['id_72' 'Product B' 'Location 70']
 ['id_73' 'Product B' 'Location 72']
 ['id_74' 'Product A' 'Location 40']
 ['id_75' 'Product A' 'Location 20']
 ['id_76' 'Product A' 'Location 73']
 ['id_77' 'Product A' 'Location 20']
 ['id_78' 'Product D' 'Location 75']
 ['id_79' 'Product D' 'Location 76']
 ['id_80' 'Product D' 'Location 77']
 ['id_81' 'Product A' 'Location 2']
 ['id_82' 'Product B' 'Location 4']
 ['id_83' 'Product A' 'Location 78']
 ['id_84' 'Product D' 'Location 79']
 ['id_85' 'Product B' 'Location 80']]

***Partial Cleaning While Importing - Exercise #3***
Display the contents of lending_co_TP to the console.
Load only the first and last columns of the "Lending-Company-Total-Price-100.csv" file into a two-dimensional array named lending_co_TP, using a comma as the delimiter, a string data type, and skipping the first row.

In [7]:
data = np.genfromtxt("Lending-Company-Total-Price-100.csv", usecols=(0,6),delimiter=',',dtype=str,skip_header=1)
lending_co_TP = np.array(data)
print(lending_co_TP)

[['"1' '16600"']
 ['"2' '16600"']
 ['"3' '15600"']
 ['"4' '16600"']
 ['"5' '20250"']
 ['"6' '"']
 ['"7' '20250"']
 ['"8' '16600"']
 ['"9' '22250"']
 ['"10' '20250"']
 ['"11' '16600"']
 ['"12' '20250"']
 ['"13' '16600"']
 ['"14' '20750"']
 ['"15' '22250"']
 ['"16' '16600"']
 ['"17' '22250"']
 ['"18' '16600"']
 ['"19' '16600"']
 ['"20' '54625"']
 ['"21' '16600"']
 ['"22' '22250"']
 ['"23' '19250"']
 ['"24' '15600"']
 ['"25' '20250"']
 ['"26' '22250"']
 ['"27' '19250"']
 ['"28' '69225"']
 ['"29' '20250"']
 ['"30' '16600"']
 ['"31' '16600"']
 ['"32' '16600"']
 ['"33' '19250"']
 ['"34' '16600"']
 ['"35' '19250"']
 ['"36' '16600"']
 ['"37' '16600"']
 ['"38' '16600"']
 ['"39' '15600"']
 ['"40' '16600"']
 ['"41' '16600"']
 ['"42' '16600"']
 ['"43' '19250"']
 ['"44' '15600"']
 ['"45' '19250"']
 ['"46' '16600"']
 ['"47' '16600"']
 ['"48' '16600"']
 ['"49' '20250"']
 ['"50' '22250"']
 ['"51' '16600"']
 ['"52' '20250"']
 ['"53' '20250"']
 ['"54' '16600"']
 ['"55' '16600"']
 ['"56' '16600"']
 ['"57' '"']
 ['"58' '16600"']
 ['"59' '16600"']
 ['"60' '16600"']
 ['"61' '19250"']
 ['"62' '15600"']
 ['"63' '15600"']
 ['"64' '20250"']
 ['"65' '16600"']
 ['"66' '22250"']
 ['"67' '22250"']
 ['"68' '20250"']
 ['"69' '20250"']
 ['"70' '16600"']
 ['"71' '15600"']
 ['"72' '16600"']
 ['"73' '16600"']
 ['"74' '22250"']
 ['"75' '20750"']
 ['"76' '22250"']
 ['"77' '19250"']
 ['"78' '20250"']
 ['"79' '20250"']
 ['"80' '20250"']
 ['"81' '19250"']
 ['"82' '16600"']
 ['"83' '22250"']
 ['"84' '20250"']
 ['"85' '16600"']
 ['"86' '19250"']
 ['"87' '22250"']
 ['"88' '16600"']
 ['"89' '19250"']
 ['"90' '16600"']
 ['"91' '"']
 ['"92' '20250"']
 ['"93' '16600"']
 ['"94' '16600"']
 ['"95' '19250"']
 ['"96' '16600"']
 ['"97' '16600"']
 ['"98' '22250"']
 ['"99' '22250"']
 ['"100' '16600"']]

***Partial Cleaning While Importing - Exercise #4***
Similar to the previous exercise, load only the first and last columns of the "Lending-Company-Total-Price-100.csv" file into a two-dimensional array named lending_co_TP, using a comma as the delimiter and skipping the first row. This time, however, use 32-bit NumPy float data types.

Display the contents of lending_co_TP to the console.

In [8]:
lending_co_TP = np.array(np.genfromtxt("Lending-Company-Total-Price-100.csv", usecols=(0,6),delimiter=',',skip_header=1,dtype=(float)))
print(lending_co_TP)

[[nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]
 [nan nan]]